---
# This playbook documents all servers maintained by ansible

- name: Get Device Facts
  hosts: all
  vars_files:
    - dokuwiki_vars.yml
  tasks:

### Caching facts
  - name: Display all variables/facts known for each server
    debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.address }} {{ hostvars[inventory_hostname]["ansible_fqdn"] }} {{ hostvars[inventory_hostname]["ansible_hostname"] }}"


### Documentation files
  - name: Create the directorys for the description files on each server
    file: path="{{ dokuwiki_local_destination }}" state=directory owner="{{ dokuwiki_local_destination_user }}" group="{{ dokuwiki_local_destination_group }}" mode=0775

  - name: Create the description file on each server
    template:
      src: dokuwiki_templates/description.txt.j2
      dest: "{{ dokuwiki_local_destination }}/description.txt"
      owner: root
      group: root
      force: no

  - name: Download the description file
    slurp: src="{{ dokuwiki_local_destination }}/description.txt"
    register: server_description

  - name: Create the changelog file on each server
    copy: content="" dest="{{ item }}" force=no
    with_items:
      - "{{ dokuwiki_local_destination }}/changelog.txt"

  - name: Download the changelog file
    slurp: src="{{ dokuwiki_local_destination }}/changelog.txt"
    register: server_changelog

  - name: Create the notes file on each server
    copy: content="" dest="{{ item }}" force=no
    with_items:
      - "{{ dokuwiki_local_destination }}/notes.txt"

  - name: Download the notes file
    slurp: src="{{ dokuwiki_local_destination }}/notes.txt"
    register: server_notes
 

### Dokuwiki directory and file creation
- hosts: "{{ dokuwiki_targetserver }}"
  vars_files:
    - dokuwiki_vars.yml
  tasks:
    - name: Create the directorys for dokuwiki
      file: path="{{ dokuwiki_directory }}" state=directory owner="{{ dokuwiki_user }}" group="{{ dokuwiki_group }}" mode=0775

    - name: Place the serverlist template
      template:
        src: dokuwiki_templates/serverlist.txt.j2
        dest: "{{ dokuwiki_serverlist_destination }}"
        owner: "{{ dokuwiki_user }}"
        group: "{{ dokuwiki_group }}"

- hosts: all
  vars_files:
    - dokuwiki_vars.yml
  gather_facts: true
  tasks:

    - name: Place each server as a wikipage on {{ dokuwiki_targetserver }}:{{ dokuwiki_directory }}/
      template:
        src: dokuwiki_templates/server.txt.j2
        dest: "{{ dokuwiki_directory }}/{{ inventory_hostname }}.txt"
        owner: "{{ dokuwiki_user }}"
        group: "{{ dokuwiki_group }}"
      delegate_to: "{{ dokuwiki_targetserver }}"

  
