---
# This playbook documents all servers maintained by ansible

- name: Debug playboek voor alle variabelen
  hosts: all
  vars_files:
    - dokuwiki_vars.yml
  tasks:
  - name: Display all variables/facts known for a host
    debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.address }} {{ hostvars[inventory_hostname]["ansible_fqdn"] }} {{ hostvars[inventory_hostname]["ansible_hostname"] }}"


- hosts: all
  vars_files:
    - dokuwiki_vars.yml
  tasks:
    - name: Plaats template met alle servers
      template:
        src: dokuwiki_templates/description.txt.j2
        dest: /root/description.txt
        owner: root
        group: root
        force: no

    - name: maak de description en changelog files aan
      copy: content="" dest="{{ item }}" force=no
      with_items:
        - /root/changelog.txt
        - /root/notes.txt

    - name: slurp description
      slurp: src=/root/description.txt
      register: server_description

    - name: slurp changelog
      slurp: src=/root/changelog.txt
      register: server_changelog

    - name: slurp notes
      slurp: src=/root/notes.txt
      register: server_notes
 

- hosts: "{{ dokuwiki_targetserver }}"
  vars_files:
    - dokuwiki_vars.yml
  tasks:
    - name: maak de ka linux ansible directorys aan
      file: path="{{ dokuwiki_directory }}" state=directory owner="{{ dokuwiki_user }}" group="{{ dokuwiki_group }}" mode=0775

    - name: Plaats template met alle serverlinks
      template:
        src: dokuwiki_templates/serverlist.txt.j2
        dest: "{{ dokuwiki_serverlist_destination }}"
        owner: "{{ dokuwiki_user }}"
        group: "{{ dokuwiki_group }}"

- hosts: all
  vars_files:
    - dokuwiki_vars.yml
  gather_facts: true
  tasks:

    - name: Plaats template met alle servers
      template:
        src: dokuwiki_templates/server.txt.j2
        dest: "{{ dokuwiki_directory }}/{{ inventory_hostname }}.txt"
        owner: "{{ dokuwiki_user }}"
        group: "{{ dokuwiki_group }}"
      delegate_to: "{{ dokuwiki_targetserver }}"

  
